esphome:
  name: printer-led

esp8266:
  board: d1_mini
#  framework:
#    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yourkey"

ota:
  password: "yourpassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Printer-Led Fallback Hotspot"
    password: "yourpassword"

captive_portal:

light:
  - platform: neopixelbus
    type: GRB  
    variant: WS2812
    pin: D4
    num_leds: 13
    name: "FastLED WS2811 Light 1"
    restore_mode: ALWAYS_ON 
  - platform: neopixelbus
    type: GRB  
    variant: WS2812
    pin: D3
    num_leds: 13
    name: "FastLED WS2811 Light 2"
    restore_mode: ALWAYS_ON 
